name: Appium iOS Safari Tests

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'
      - 'tests/static_tests/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - '.gitignore'
      - 'mops/__init__.py'
  pull_request:

jobs:
  ios-tests:
    runs-on: macos-15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        id: setup
        uses: ./.github/actions/setup
        with:
          python-version: '3.10'

      - uses: actions/setup-node@v6
        with:
          node-version: '25.2.1'

      - name: Install Appium & UiAutomator2 Driver
        run: |
          npm install -g npm@11.6.4
          npm install -g appium@3.1.2
          appium driver install xcuitest@10.14.1

      - name: Start Appium Server in the Background
        run: |
          nohup appium > appium.log 2>&1 &
          sleep 10

      - name: Run Appium Safari tests
        id: tests
        timeout-minutes: 30
        run: |
          uv run --no-config pytest tests/web_tests --platform ios --driver safari -v --alluredir=allure-report --reruns=2 -m='not low'
        continue-on-error: true

      - name: Teardown (Allure Report and Error Handling)
        if: ${{ steps.tests.outcome == 'failure' }}
        uses: ./.github/actions/teardown
        with:
          browser-name: "safari"
          engine: "appium"
