name: Ruff

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          python-version: '3.12'

      - name: Ruff lint
        run: uv run ruff check

      - name: Ruff format
        run: uv run ruff format --check
